/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [62.26KB] > C:\Users\Asus\Downloads\3d_character_young_boy\scene-transformed.glb [618.42KB] (-893%)
Author: Sunny (https://sketchfab.com/sanaullahrais)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-character-young-boy-60dfa6ac87e84e7dae8dba220526946d
Title: 3D Character Young Boy
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function HomeModel(props) {
    const { nodes, materials } = useGLTF('/models/scene-transformed.glb')
    const modelRef = useRef()
    useFrame((state, delta, xrFrame) => {
        // console.log(state.clock);
        modelRef.current.position.y = -2 + Math.sin(state.clock.elapsedTime) * 0.2
    })
    return (
        <group {...props} dispose={null}
            ref={modelRef}
            position={[-3.3, -0.8, 0]}
            scale={[2.2, 2.2, 2.2]}
            rotation={[0.25, 0.5, -0.15]}
        // position={[0, 0, 0]}
        // scale={[2.2, 2.2, 2.2]}
        // rotation={[0.25, 0, 0]}
        >
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_9.skeleton} />
            <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Object_11.skeleton} />
            <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Object_13.skeleton} />
            <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Object_15.skeleton} />
            <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Object_17.skeleton} />
            <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Object_19.skeleton} />
            <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Object_21.skeleton} />
            <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_23.skeleton} />
            <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Object_25.skeleton} />
        </group>
    )
}

useGLTF.preload('/models/scene-transformed.glb')
